title: Syifa Nadhira Fahira # your name (or website title) here
logo: "/images/Syifa_Image.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br>PZSIB<br>
 
  <br>Undergraduate Statistics Student at Padjadjaran University<br>
  <a href="https://www.linkedin.com/in/syifanadhirafahira/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
